import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Button, ButtonArrow } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Eyebrow } from "@/components/ui/eyebrow";
import { Placeholder } from "@/components/ui/placeholder";
import { CreditDot } from "@/components/ui/credit-dot";
import { Price } from "@/components/ui/price";
import { Faq } from "@/components/ui/faq";
import { Nav } from "@/components/marketing/nav";
import { Reveal } from "@/components/marketing/reveal";
import { Logo } from "@/components/marketing/logo";
import { HeroTransform } from "@/components/marketing/hero-transform";
import { CheckIcon, WhyIcon } from "@/components/marketing/icons";
import { StructuredData } from "@/components/marketing/structured-data";
import { STEPS, STYLES, WHY, PLANS, ADDONS, FAQ } from "@/lib/landing-content";
import { publicPageMetadata, siteConfig } from "@/lib/seo";
import { createSupabaseServerClient } from "@/lib/supabase/server";

export const metadata: Metadata = {
  ...publicPageMetadata({
    title: `AI Headshot Generator - Studio Quality in Minutes | ${siteConfig.name}`,
    description:
      "Upload selfies and get professional AI headshots for LinkedIn, resumes, websites, and business profiles. Personal model training, fast generation, and clear pricing.",
    path: "/"
  }),
  title: {
    absolute: `AI Headshot Generator - Studio Quality in Minutes | ${siteConfig.name}`
  }
};

const CONTACT_EMAIL = siteConfig.supportEmail;

type PlanFeature = { text: string; strong?: string; lead?: boolean };

function Feature({ f }: { f: PlanFeature }) {
  return (
    <li>
      <CheckIcon />
      <span>
        {f.lead ? <span className="hl">{f.text}</span> : f.text}
        {f.strong}
      </span>
    </li>
  );
}

// Links the support email inside the refund answer while leaving other answers as plain text.
function answerNode(a: string) {
  if (!a.includes(CONTACT_EMAIL)) return a;
  const [before, after] = a.split(CONTACT_EMAIL);
  return (
    <>
      {before}
      <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>
      {after}
    </>
  );
}

export default async function LandingPage() {
  const supabase = await createSupabaseServerClient();
  const {
    data: { user }
  } = await supabase.auth.getUser();
  const authenticated = Boolean(user);

  return (
    <div className="min-h-screen bg-bg leading-[1.6] text-ink">
      <Nav authenticated={authenticated} />

      <main id="top">
        {/* ===================== HERO ===================== */}
        <section className="hero" aria-labelledby="hero-h1">
          <div className="wrap hero-grid">
            <div className="hero-copy">
              <Reveal as="span" className="eyebrow">
                AI headshot studio
              </Reveal>
              <Reveal as="h1" delay={1}>
                <span id="hero-h1">
                  Your professional headshot, <em>generated by AI</em>
                </span>
              </Reveal>
              <Reveal as="p" delay={2} className="sub">
                Upload your selfies, we train a model on your face, you get
                studio-quality headshots in minutes. No photographer. No studio.
              </Reveal>
              <Reveal delay={2} className="hero-cta">
                <Button asChild variant="pill" size="pill">
                  <Link href={authenticated ? "/dashboard/headshots" : "/login"}>
                    {authenticated ? "Open dashboard" : "Get my headshots"} <ButtonArrow />
                  </Link>
                </Button>
                <a href="#how-it-works" className="linklike">
                  See how it works ↓
                </a>
              </Reveal>
              <Reveal delay={3} className="social-proof">
                <span className="avatars" aria-hidden="true">
                  <span className="av">
                    <i />
                  </span>
                  <span className="av">
                    <i />
                  </span>
                  <span className="av">
                    <i />
                  </span>
                  <span className="av">
                    <i />
                  </span>
                </span>
                <span>
                  Trusted by <b>1,200+ professionals</b> worldwide
                </span>
              </Reveal>
            </div>

            <Reveal delay={1} className="hero-visual">
              <div className="hero-transform-shell">
                <HeroTransform />
              </div>
            </Reveal>
          </div>
        </section>

        {/* ================= HOW IT WORKS ================= */}
        <section id="how-it-works" className="lp-section" aria-labelledby="how-h2">
          <div className="wrap">
            <Reveal className="sec-head sec-head-wide">
              <Eyebrow>How it works</Eyebrow>
              <h2 id="how-h2">Three steps to a studio-quality headshot</h2>
            </Reveal>
            <div className="steps">
              {STEPS.map((step, i) => (
                <Reveal
                  key={step.num}
                  as="article"
                  delay={(i || undefined) as 1 | 2 | undefined}
                  className="step"
                >
                  <div className="ph step-shot-card" data-label="">
                    <Image
                      src={step.src}
                      alt={step.alt}
                      fill
                      sizes="(max-width: 900px) 100vw, 30vw"
                      className="step-shot-image"
                    />
                    <span className="step-shot-label">{step.label}</span>
                  </div>
                  <span className="num">{step.num}</span>
                  <h3>{step.title}</h3>
                  <p>{step.body}</p>
                </Reveal>
              ))}
            </div>
          </div>
        </section>

        {/* ===================== STYLES ===================== */}
        <section id="styles" className="lp-section" aria-labelledby="styles-h2">
          <div className="wrap">
            <Reveal className="sec-head center">
              <Eyebrow>Styles</Eyebrow>
              <h2 id="styles-h2">Choose your look</h2>
              <p>
                Every plan includes all three. Generate as many variations as your
                credits allow.
              </p>
            </Reveal>
            <div className="style-grid">
              {STYLES.map((style, i) => (
                <Reveal
                  key={style.title}
                  as="article"
                  delay={(i || undefined) as 1 | 2 | undefined}
                  className="style-card"
                >
                  <div className="ph style-shot-card" data-label="">
                    <Image
                      src={style.src}
                      alt={style.alt}
                      fill
                      sizes="(max-width: 900px) 100vw, 33vw"
                      className="style-shot-image"
                    />
                    <span className="style-shot-label">{style.label}</span>
                  </div>
                  <div className="body">
                    <span className="tag">{style.tag}</span>
                    <h3>{style.title}</h3>
                    <p>{style.body}</p>
                  </div>
                </Reveal>
              ))}
            </div>
          </div>
        </section>

        {/* ============ WHY NOT A PHOTOGRAPHER ============ */}
        <section className="lp-section" aria-labelledby="why-h2">
          <div className="wrap">
            <Reveal className="panel-navy">
              <div className="sec-head">
                <Eyebrow>Why {siteConfig.name}</Eyebrow>
                <h2 id="why-h2">Better than a photoshoot. Here&apos;s why.</h2>
              </div>
              <div className="why-grid">
                {WHY.map((item) => (
                  <div className="why-item" key={item.title}>
                    <WhyIcon name={item.icon} />
                    <h3>{item.title}</h3>
                    <p>{item.body}</p>
                  </div>
                ))}
              </div>
            </Reveal>
          </div>
        </section>

        {/* ===================== PRICING ===================== */}
        <section id="pricing" className="lp-section" aria-labelledby="pricing-h2">
          <div className="wrap">
            <Reveal className="sec-head center">
              <Eyebrow>Pricing</Eyebrow>
              <h2 id="pricing-h2">Monthly plans, plus credit packs when you need them.</h2>
            </Reveal>

            <div className="price-grid">
              {/* Starter */}
              <Reveal as="article" className="plan">
                <h3 className="pname">{PLANS.starter.name}</h3>
                <Price amount={PLANS.starter.price} suffix="one-time" />
                <p className="pdesc">{PLANS.starter.desc}</p>
                <ul>
                  {PLANS.starter.features.map((f, i) => (
                    <Feature key={i} f={f} />
                  ))}
                </ul>
                <Button asChild variant="pillGhost" size="pill" className="w-full">
                  <Link href="/pricing">
                    {PLANS.starter.cta} <ButtonArrow />
                  </Link>
                </Button>
              </Reveal>

              {/* Pro */}
              <Reveal as="article" delay={1} className="plan pro">
                <Badge variant="gold" className="absolute -top-[13px] left-[34px]">
                  Most popular
                </Badge>
                <h3 className="pname">{PLANS.pro.name}</h3>
                <Price amount={PLANS.pro.price} suffix="one-time" />
                <p className="pdesc">{PLANS.pro.desc}</p>
                <ul>
                  {PLANS.pro.features.map((f, i) => (
                    <Feature key={i} f={f} />
                  ))}
                </ul>
                <Button asChild variant="pillGold" size="pill" className="w-full">
                  <Link href="/pricing">
                    {PLANS.pro.cta} <ButtonArrow />
                  </Link>
                </Button>
              </Reveal>
            </div>

            <Reveal className="addons">
              {ADDONS.map((a, i) => (
                <div className="addon" key={i}>
                  <span>
                    {a.text}
                    <b>{a.strong}</b>
                  </span>
                  <span className="ad-price">{a.price}</span>
                </div>
              ))}
            </Reveal>

            <Reveal className="credits-note">
              <div className="row">
                <CreditDot tone="blue" />
                <span>
                  <b>Blue credits</b> generate images — low quality: 1 cr · medium: 2
                  cr · high: 3 cr.
                </span>
              </div>
              <div className="row">
                <CreditDot tone="gold" />
                <span>
                  <b>Golden credits</b> train a personal AI model on your photos — 1
                  model = 1 golden credit.
                </span>
              </div>
            </Reveal>
          </div>
        </section>

        {/* ======================= FAQ ======================= */}
        <section id="faq" className="lp-section" aria-labelledby="faq-h2">
          <div className="wrap">
            <Reveal className="sec-head center">
              <Eyebrow>FAQ</Eyebrow>
              <h2 id="faq-h2">Common questions</h2>
            </Reveal>
            <Reveal className="faq-wrap">
              <Faq
                items={FAQ.map((f) => ({ question: f.q, answer: answerNode(f.a) }))}
              />
            </Reveal>
          </div>
        </section>
      </main>

      {/* ======================= FOOTER ======================= */}
      <footer className="site-footer">
        <div className="wrap">
          <Reveal className="cta-band">
            <h2>Your next headshot is ten minutes away.</h2>
            <Button asChild variant="pill" size="pill">
              <Link href="/login">
                Get my headshots <ButtonArrow />
              </Link>
            </Button>
          </Reveal>
          <div className="foot-top">
            <div className="foot-brand">
              <a href="#top" aria-label={`${siteConfig.name} home`}>
                <Logo />
              </a>
              <p>{siteConfig.tagline}</p>
            </div>
            <nav className="foot-links" aria-label="Footer">
              <Link href="/about">About</Link>
              <Link href="/terms">Terms of Service</Link>
              <Link href="/privacy">Privacy Policy</Link>
              <Link href="/cookies">Cookie Policy</Link>
              <Link href="/refund-policy">Refund Policy</Link>
              <a href={`mailto:${CONTACT_EMAIL}`}>Contact</a>
            </nav>
          </div>
          <div className="foot-bottom">
            <small>© 2026 {siteConfig.name}</small>
            <small>Made for professionals worldwide.</small>
          </div>
        </div>
      </footer>

      <StructuredData />
    </div>
  );
}
