import { Nav } from "@/components/Nav";
import { Reveal } from "@/components/Reveal";
import { Placeholder } from "@/components/Placeholder";
import { Logo } from "@/components/Logo";
import { Faq } from "@/components/Faq";
import { StructuredData } from "@/components/StructuredData";
import { CheckIcon, WhyIcon } from "@/components/icons";
import {
  HERO_SHOTS,
  STEPS,
  STYLES,
  WHY,
  PLANS,
  ADDONS,
} from "@/lib/content";

export default function Page() {
  return (
    <>
      <Nav />

      <main id="top">
        {/* ===================== HERO ===================== */}
        <section className="hero" aria-labelledby="hero-h1">
          <div className="wrap hero-grid">
            <div className="hero-copy">
              <Reveal as="span" className="eyebrow">
                AI headshot studio
              </Reveal>
              <Reveal as="h1" delay={1} className="">
                {/* id used as the single h1 + aria target */}
                <span id="hero-h1">
                  Your professional headshot, <em>generated by AI</em>
                </span>
              </Reveal>
              <Reveal as="p" delay={2} className="sub">
                Upload your selfies, we train a model on your face, you get
                studio-quality headshots in minutes. No photographer. No studio.
              </Reveal>
              <Reveal delay={2} className="hero-cta">
                <a href="#pricing" className="btn btn-primary">
                  Get my headshots <span className="arr">→</span>
                </a>
                <a href="#how-it-works" className="linklike">
                  See how it works ↓
                </a>
              </Reveal>
              <Reveal delay={3} className="social-proof">
                <div className="avatars" aria-hidden="true">
                  <span className="av"><i /></span>
                  <span className="av"><i /></span>
                  <span className="av"><i /></span>
                  <span className="av"><i /></span>
                </div>
                <span>
                  Trusted by <b>1,200+ professionals</b> worldwide
                </span>
              </Reveal>
            </div>

            <Reveal delay={1} className="hero-visual">
              <div
                className="hero-shots"
                role="group"
                aria-label="Sample AI headshots"
              >
                {HERO_SHOTS.map((s, i) => (
                  <Placeholder key={i} label={s.label} alt={s.alt} />
                ))}
              </div>
            </Reveal>
          </div>
        </section>

        {/* ================= HOW IT WORKS ================= */}
        <section id="how-it-works" aria-labelledby="how-h2">
          <div className="wrap">
            <Reveal className="sec-head">
              <span className="eyebrow">How it works</span>
              <h2 id="how-h2">Three steps to a studio-quality headshot</h2>
            </Reveal>
            <div className="steps">
              {STEPS.map((step, i) => (
                <Reveal
                  key={step.num}
                  as="article"
                  delay={(i || undefined) as 1 | 2 | undefined}
                  className="step"
                >
                  <Placeholder label={step.label} alt={step.alt} />
                  <span className="num">{step.num}</span>
                  <h3>{step.title}</h3>
                  <p>{step.body}</p>
                </Reveal>
              ))}
            </div>
          </div>
        </section>

        {/* ===================== STYLES ===================== */}
        <section id="styles" aria-labelledby="styles-h2">
          <div className="wrap">
            <Reveal className="sec-head center">
              <span className="eyebrow">Styles</span>
              <h2 id="styles-h2">Choose your look</h2>
              <p>
                Every plan includes all three. Generate as many variations as
                your credits allow.
              </p>
            </Reveal>
            <div className="style-grid">
              {STYLES.map((style, i) => (
                <Reveal
                  key={style.title}
                  as="article"
                  delay={(i || undefined) as 1 | 2 | undefined}
                  className="style-card"
                >
                  <Placeholder label={style.label} alt={style.alt} />
                  <div className="body">
                    <span className="tag">{style.tag}</span>
                    <h3>{style.title}</h3>
                    <p>{style.body}</p>
                  </div>
                </Reveal>
              ))}
            </div>
          </div>
        </section>

        {/* ============ WHY NOT A PHOTOGRAPHER ============ */}
        <section aria-labelledby="why-h2">
          <div className="wrap">
            <Reveal className="why">
              <div className="sec-head">
                <span className="eyebrow">Why headshotly</span>
                <h2 id="why-h2">Better than a photoshoot. Here&apos;s why.</h2>
              </div>
              <div className="why-grid">
                {WHY.map((item) => (
                  <div className="why-item" key={item.title}>
                    <WhyIcon name={item.icon} />
                    <h3>{item.title}</h3>
                    <p>{item.body}</p>
                  </div>
                ))}
              </div>
            </Reveal>
          </div>
        </section>

        {/* ===================== PRICING ===================== */}
        <section id="pricing" aria-labelledby="pricing-h2">
          <div className="wrap">
            <Reveal className="sec-head center">
              <span className="eyebrow">Pricing</span>
              <h2 id="pricing-h2">
                Simple, one-time pricing. No subscriptions.
              </h2>
            </Reveal>

            <div className="price-grid">
              {/* Starter */}
              <Reveal as="article" className="plan">
                <span className="pname">{PLANS.starter.name}</span>
                <div className="price">
                  {PLANS.starter.price} <small>one-time</small>
                </div>
                <p className="pdesc">{PLANS.starter.desc}</p>
                <ul>
                  {PLANS.starter.features.map((f, i) => (
                    <li key={i}>
                      <CheckIcon />
                      <span>
                        {f.lead ? <span className="hl">{f.text}</span> : f.text}
                        {f.strong}
                      </span>
                    </li>
                  ))}
                </ul>
                <a href="#" className="btn btn-ghost">
                  {PLANS.starter.cta} <span className="arr">→</span>
                </a>
              </Reveal>

              {/* Pro */}
              <Reveal as="article" delay={1} className="plan pro">
                <span className="badge">Most popular</span>
                <span className="pname">{PLANS.pro.name}</span>
                <div className="price">
                  {PLANS.pro.price} <small>one-time</small>
                </div>
                <p className="pdesc">{PLANS.pro.desc}</p>
                <ul>
                  {PLANS.pro.features.map((f, i) => (
                    <li key={i}>
                      <CheckIcon />
                      <span>
                        {f.lead ? <span className="hl">{f.text}</span> : f.text}
                        {f.strong}
                      </span>
                    </li>
                  ))}
                </ul>
                <a href="#" className="btn btn-primary">
                  {PLANS.pro.cta} <span className="arr">→</span>
                </a>
              </Reveal>
            </div>

            <Reveal className="addons">
              {ADDONS.map((a, i) => (
                <div className="addon" key={i}>
                  <span>
                    {a.text}
                    <b>{a.strong}</b>
                  </span>
                  <span className="ad-price">{a.price}</span>
                </div>
              ))}
            </Reveal>

            <Reveal className="credits-note">
              <div className="row">
                <span className="cdot blue" />
                <span>
                  <b>Blue credits</b> generate images — low quality: 1 cr ·
                  medium: 2 cr · high: 3 cr.
                </span>
              </div>
              <div className="row">
                <span className="cdot gold" />
                <span>
                  <b>Golden credits</b> train a personal AI model on your
                  photos — 1 model = 1 golden credit.
                </span>
              </div>
            </Reveal>
          </div>
        </section>

        {/* ======================= FAQ ======================= */}
        <section id="faq" aria-labelledby="faq-h2">
          <div className="wrap">
            <Reveal className="sec-head center">
              <span className="eyebrow">FAQ</span>
              <h2 id="faq-h2">Common questions</h2>
            </Reveal>
            <Reveal>
              <Faq />
            </Reveal>
          </div>
        </section>
      </main>

      {/* ======================= FOOTER ======================= */}
      <footer className="site-footer">
        <div className="wrap">
          <Reveal className="cta-band">
            <h2>Your next headshot is ten minutes away.</h2>
            <a href="#pricing" className="btn btn-primary">
              Get my headshots <span className="arr">→</span>
            </a>
          </Reveal>
          <div className="foot-top">
            <div className="foot-brand">
              <a href="#top">
                <Logo />
              </a>
              <p>Studio-quality headshots, generated by AI.</p>
            </div>
            <nav className="foot-links" aria-label="Footer">
              <a href="#">Privacy Policy</a>
              <a href="#">Terms of Service</a>
              <a href="mailto:hello@headshotly.pro">Contact</a>
            </nav>
          </div>
          <div className="foot-bottom">
            <small>© 2026 headshotly.pro</small>
            <small>Made for professionals worldwide.</small>
          </div>
        </div>
      </footer>

      <StructuredData />
    </>
  );
}
